#!/bin/bash

INPUT="$1"
MIDPUT="partial_sort.log"
OUTPUT="${INPUT##*/}-pull_bound_headers.log"

mawk_prog='BEGIN {isHeaderLine=0;}
{
	if (match($0, "^[0-9]+,"))
	{
		isHeaderLine=1;
	}
	else if (isHeaderLine)
	{
		gsub(",\t+", " ");
		print $0;
		isHeaderLine=0;
	}
}'

if [ -f "$MIDPUT" ]; then rm "$MIDPUT"; fi

mawk "$mawk_prog" "$INPUT" |
while read line
do
	echo "$line" |
	mawk '{ gsub(" ", "\n"); print $0; }' |
	sort |
	mawk 'BEGIN { acc=""; } { acc=acc", "$0; } END { print substr(acc, 3, length(acc)); }' >> "$MIDPUT"
done

sort -u "$MIDPUT" > "$OUTPUT"
rm "$MIDPUT"

